CREATE DATABASE JussaCalls
GO
USE JussaCalls
GO
CREATE TABLE Usuario
(
UsuarioID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Nome VARCHAR(50) NOT NULL,
Email VARCHAR(60) NOT NULL UNIQUE,
Senha VARBINARY(32),
NIF VARCHAR(11) UNIQUE,
)
GO
CREATE TABLE StatusItem
(
StatusID INT PRIMARY KEY IDENTITY(1,1), 
NomeStatus NVARCHAR(20)
)
GO
CREATE TABLE Fila
(
FilaID INT PRIMARY KEY IDENTITY(1,1),
NomeFila VARCHAR(20)
)

GO

CREATE TABLE Localizacao2
(
LocalizacaoID INT PRIMARY KEY,
Nome VARCHAR(25) NOT NULL,
Andar INT IDENTITY(1,1) NOT NULL
)

GO
CREATE TABLE OrdemServico
(
OS_ID INT PRIMARY KEY IDENTITY(1,1),
NomeItem VARCHAR(50) NOT NULL,
dataCriacao DATETIME2(0) NOT NULL,
Descricao NVARCHAR(255) NOT NULL,
Imagem VARBINARY(32),

StatusID INT NOT NULL,
usuarioSolicitante UNIQUEIDENTIFIER NOT NULL,
FilaID INT NOT NULL,
LocalizacaoID INT NOT NULL,

CONSTRAINT OS_FilaID_FK FOREIGN KEY(FilaID) 
REFERENCES Fila(FilaID) ON DELETE CASCADE,

CONSTRAINT OS_usuarioSolicitante_FK FOREIGN KEY(usuarioSolicitante) 
REFERENCES Usuario(UsuarioID) ON DELETE CASCADE,

CONSTRAINT OS_Status_FK FOREIGN KEY(StatusID) 
REFERENCES StatusItem(StatusID) ON DELETE CASCADE,

CONSTRAINT OS_Localizacao_FK FOREIGN KEY(LocalizacaoID)
REFERENCES Localizacao2(LocalizacaoID) ON DELETE CASCADE

)


