// <auto-generated />
using System;
using ChamaJussa_API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChamaJussa_API.Migrations
{
    [DbContext(typeof(JussaCalls2Context))]
    [Migration("20260821001258_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChamaJussa_API.Domains.Fila", b =>
                {
                    b.Property<int>("FilaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilaID"));

                    b.Property<string>("NomeFila")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("FilaID")
                        .HasName("PK__Fila__6E0F8A59AF24E1DA");

                    b.ToTable("Fila");
                });

            modelBuilder.Entity("ChamaJussa_API.Domains.Localizacao", b =>
                {
                    b.Property<int>("LocalizacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalizacaoID"));

                    b.Property<string>("Andar")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("LocalizacaoID")
                        .HasName("PK__Localiza__83ABDECACA4D1030");

                    b.ToTable("Localizacao");
                });

            modelBuilder.Entity("ChamaJussa_API.Domains.OrdemServico", b =>
                {
                    b.Property<int>("OS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OS_ID"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("FilaID")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("LocalizacaoID")
                        .HasColumnType("int");

                    b.Property<string>("NomeItem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataCriacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid?>("usuarioSolicitante")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OS_ID")
                        .HasName("PK__OrdemSer__85A506ED81A76118");

                    b.HasIndex("FilaID");

                    b.HasIndex("LocalizacaoID");

                    b.HasIndex("StatusID");

                    b.HasIndex("usuarioSolicitante");

                    b.ToTable("OrdemServico");
                });

            modelBuilder.Entity("ChamaJussa_API.Domains.Status_OS", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("NomeStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("StatusID")
                        .HasName("PK__Status_O__C8EE2043AEE983F5");

                    b.ToTable("Status_OS");
                });

            modelBuilder.Entity("ChamaJussa_API.Domains.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("Senha")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<bool?>("StatusUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("UsuarioID")
                        .HasName("PK__Usuario__2B3DE7989F3998A8");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuario__A9D10534FF5BE9A0")
                        .IsUnique();

                    b.HasIndex(new[] { "NIF" }, "UQ__Usuario__C7DEC330F05C5805")
                        .IsUnique();

                    b.ToTable("Usuario", t =>
                        {
                            t.HasTrigger("trg_Usuario_SoftDelete");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ChamaJussa_API.Domains.OrdemServico", b =>
                {
                    b.HasOne("ChamaJussa_API.Domains.Fila", "Fila")
                        .WithMany("OrdemServico")
                        .HasForeignKey("FilaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("OS_FilaID_FK");

                    b.HasOne("ChamaJussa_API.Domains.Localizacao", "Localizacao")
                        .WithMany("OrdemServico")
                        .HasForeignKey("LocalizacaoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("OS_Localizacao_FK");

                    b.HasOne("ChamaJussa_API.Domains.Status_OS", "Status")
                        .WithMany("OrdemServico")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("OS_Status_FK");

                    b.HasOne("ChamaJussa_API.Domains.Usuario", "usuarioSolicitanteNavigation")
                        .WithMany("OrdemServico")
                        .HasForeignKey("usuarioSolicitante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("OS_usuarioSolicitante_FK");

                    b.Navigation("Fila");

                    b.Navigation("Localizacao");

                    b.Navigation("Status");

                    b.Navigation("usuarioSolicitanteNavigation");
                });

            modelBuilder.Entity("ChamaJussa_API.Domains.Fila", b =>
                {
                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("ChamaJussa_API.Domains.Localizacao", b =>
                {
                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("ChamaJussa_API.Domains.Status_OS", b =>
                {
                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("ChamaJussa_API.Domains.Usuario", b =>
                {
                    b.Navigation("OrdemServico");
                });
#pragma warning restore 612, 618
        }
    }
}
